import { AgentProfile, ExecutionStep } from './types';

/**
 * Agent Executioner Service
 * Connects the frontend to the Rust backend for AI task processing
 * and on-chain settlement.
 */

const API_BASE_URL = 'http://localhost:3001';

export interface AgentExecutionResult {
  result: string;
  resultHash: string;
  processingTime: number;
  signature?: string;
}

/**
 * Execute an agent task by calling the Rust backend.
 */
export async function executeAgentTask(
  agent: AgentProfile,
  prompt: string,
  jobId: string,
  employer: string,
  amount: number,
  onStepUpdate: (stepIndex: number, status: ExecutionStep['status'], detail?: string) => void
): Promise<AgentExecutionResult> {
  const startTime = Date.now();

  try {
    // Step 0: Validating task
    onStepUpdate(0, 'active', 'Validating task parameters...');
    await delay(500);
    onStepUpdate(0, 'completed', 'Task validated');

    // Step 1: Initializing agent
    onStepUpdate(1, 'active', `Booting ${agent.name} neural core...`);
    
    // We can call /health or /api/agent/info here to verify backend is up
    const healthRes = await fetch(`${API_BASE_URL}/health`).catch(() => null);
    
    if (healthRes?.ok) {
      // Real Backend Flow
      onStepUpdate(1, 'completed', `${agent.name} initialized`);

      // Step 2: Processing (Execute AI Task)
      onStepUpdate(2, 'active', 'Processing task via AI Executioner...');
      
      const executeRes = await fetch(`${API_BASE_URL}/api/job/execute`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          job_id: jobId,
          agent_id: agent.id,
          prompt: prompt,
          employer: employer,
          amount: amount
        })
      });

      if (!executeRes.ok) {
        const err = await executeRes.text();
        throw new Error(`AI Execution failed: ${err}`);
      }

      const executeData = await executeRes.json();
      onStepUpdate(2, 'completed', 'Processing complete');

      // Step 3: Generating proof
      onStepUpdate(3, 'active', 'Computing cryptographic proof-of-work...');
      await delay(1000);
      onStepUpdate(3, 'completed', `Hash: ${executeData.result_hash.slice(0, 16)}...`);

      // Step 4: Completing job (On-chain settlement)
      onStepUpdate(4, 'active', 'Requesting on-chain settlement...');
      
      const completeRes = await fetch(`${API_BASE_URL}/api/job/complete`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          job_id: jobId,
          employer: employer,
          result_hash: executeData.result_hash
        })
      });

      if (!completeRes.ok) {
        const err = await completeRes.text();
        throw new Error(`On-chain settlement failed: ${err}`);
      }

      const completeData = await completeRes.json();
      onStepUpdate(4, 'completed', 'Payment released');

      const processingTime = Date.now() - startTime;

      return { 
        result: executeData.result, 
        resultHash: executeData.result_hash, 
        processingTime,
        signature: completeData.signature
      };
    } else {
      // Mock Fallback Flow (If backend is unreachable)
      console.warn("[AIGENT Bridge] Backend unreachable. Falling back to client-side mock.");
      
      onStepUpdate(1, 'completed', `${agent.name} initialized (Mock)`);
      
      onStepUpdate(2, 'active', 'Processing task via Client-side Neural Engine...');
      await delay(2000);
      
      const mockResult = `## ${agent.name} ANALYSIS REPORT\n\nTask: ${prompt}\n\n[MOCK RESULT] This is a simulated response because the Rust backend is not running. In a real deployment, this would be generated by GPT-4o or Grok and verified on the Solana blockchain.`;
      const mockHash = "mock_" + Math.random().toString(36).substring(2, 15);
      
      onStepUpdate(2, 'completed', 'Processing complete');

      onStepUpdate(3, 'active', 'Computing cryptographic proof-of-work...');
      await delay(1000);
      onStepUpdate(3, 'completed', `Hash: ${mockHash.slice(0, 16)}...`);

      onStepUpdate(4, 'active', 'Simulating on-chain settlement...');
      await delay(1500);
      onStepUpdate(4, 'completed', 'Payment released (Simulated)');

      const processingTime = Date.now() - startTime;

      return { 
        result: mockResult, 
        resultHash: mockHash, 
        processingTime,
        signature: "simulated_signature_" + Math.random().toString(36).substring(2, 15)
      };
    }
  } catch (error) {
    console.error("[AIGENT Bridge] Error:", error);
    throw error;
  }
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
